create table candidate
(id bigint generated by default as identity,
 first_name varchar(255) not null,
 last_name varchar(255) not null,
 current_company varchar(255) not null,
 current_title varchar(255) not null,
 phone numeric not null,
 email_id varchar(255) not null,
 status varchar(255) not null,
 created_at timestamp not null DEFAULT CURRENT_TIMESTAMP,
 primary key (id))